name: Deploy to S3

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download npm build files
        uses: actions/download-artifact@v2
        with:
          name: dist
      - name: Display structure of downloaded files
        run: ls -R
      - name: todo deploy - Print the index.html
        shell: bash
        run: |
          value=`cat index.html`
          echo The html file is $value